# Generated by Django 5.0.6 on 2024-05-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('date_of_sale', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('discount', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.customers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.products')),
            ],
        ),
    ]
